name: "[Deploy] Build and deploy"
on:
  push:
    branches:
      - master
    tags:
      - v**
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6.9'
          architecture: 'x64'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
      - name: Build package
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "::set-env name=PACKAGE_VERSION::${GITHUB_REF/refs\/tags\/v/}"
          pip install --upgrade setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Publish to pypi
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          pip install twine
          twine upload --skip-existing dist/*



